version: "3.7"

services:
  city24:
    image: city24-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"
    expose:
      - "7629"

  pynginx:
    image: nginx
    container_name: pynginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - city24

